### ISSUE TITLE
How to implement this in an auto regressive LM?

### ISSUE THREAD

**Issue by Deaddawn** [PolymathicAI/xVal#1]
Hi, great work! I am wondering if there are more details about implementing xval encode in an auto regressive model since you have mentioned this in your paper. Thanks.

**Comment by MilesCranmer** [comment]
Code just got pushed – check it out!

**Comment by golkar** [comment]
> Hi, great work! I am wondering if there are more details about implementing xval encode in an auto regressive model since you have mentioned this in your paper. Thanks.

For autoregressive implementation, you can just set the is_causal flag of Nomformer.numformer to True when initializing an instance of the model. That way, you will have the causal mask that you need for autoregressive prediction just as in a normal transformer model.

**Comment by Deaddawn** [comment]
> > Hi, great work! I am wondering if there are more details about implementing xval encode in an auto regressive model since you have mentioned this in your paper. Thanks.
> 
> For autoregressive implementation, you can just set the is_causal flag of Nomformer.numformer to True when initializing an instance of the model. That way, you will have the causal mask that you need for autoregressive prediction just as in a normal transformer model.

Got it. Thanks!!
