### ISSUE TITLE
data generate

### ISSUE THREAD

**Issue by Deaddawn** [PolymathicAI/xVal#2]
Hi, there. How do we generate dataset using rebound exactly as mentioned in your demo

**Comment by Deaddawn** [comment]
ls it possible to provide the dataset?

**Comment by tung-nd** [comment]
I have the same question. Can the author provide the script for generating data?

**Comment by MilesCranmer** [comment]
@golkar which script is it? Do I have it or do you?

**Comment by tung-nd** [comment]
if anyone can share the data generation script for this task (and others if possible), it would be much appreciated :)

**Comment by golkar** [comment]
Code for generating more samples for the planet dataset is now included in the planets-sim folder. Instructions are given in the xval_demo notebook.

**Comment by tung-nd** [comment]
thank you for your help in this matter!
