### ISSUE TITLE
positional embedding

### ISSUE THREAD

**Issue by tung-nd** [PolymathicAI/xVal#5]
The paper said "the multiplicative embedding of XVAL is followed by the addition of a positional encoding vector", but in the code the addition of positional embedding is before the multiplication. Is this expected?

https://github.com/PolymathicAI/xVal/blob/main/xval/numformer.py#L59

**Comment by golkar** [comment]
This is indeed a bug introduced when we refactored our internal code for public release. It has been fixed in the latest commit.
